import test from 'node:test';
import assert from 'node:assert/strict';
import {newProject,parseProject,cloneProject,addVariant,setAttachmentKey,sampleAttachment,variantPart,blink,worldBones,partCorners,movePivot} from '../dist/model.js';
import {exportSpine,usedAssets} from '../dist/spine.js';
import {hexRGB,keyRaster,backgroundReport,componentRects,cropRaster,brushMask,alphaStats,recommendColor} from '../dist/chroma.js';
import {newPreparation,parsePreparation,partsPrompt,specsFor,approveCandidate,coverage} from '../dist/production.js';
const pixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLttAAAAABJRU5ErkJggg==';
function character(){const p=newProject();p.assets=[{id:'open',name:'睁眼',width:80,height:60,hasAlpha:true,dataUrl:pixel},{id:'closed',name:'闭眼',width:75,height:20,hasAlpha:true,dataUrl:pixel}];p.parts=[{id:'eye',name:'眼睛',assetId:'open',boneId:'root',x:20,y:-180,rotation:23,scaleX:-1.2,scaleY:.8,pivotX:.2,pivotY:.8,z:0,opacity:1,visible:true,locked:false}];return p;}
function raster(bg=[0,255,0],w=20,h=20){const data=new Uint8ClampedArray(w*h*4);for(let i=0;i<data.length;i+=4)data.set([...bg,255],i);return {width:w,height:h,data};}
function rect(r,x0,y0,w,h,color=[220,150,180]){for(let y=y0;y<y0+h;y++)for(let x=x0;x<x0+w;x++)r.data.set([...color,255],(y*r.width+x)*4);}
const options={color:[0,255,0],inner:18,outer:95,despill:true};
test('v0.2 projects migrate to v0.3 without mutating input',()=>{const old=character();old.version='0.2';const n=parseProject(old);assert.equal(old.version,'0.2');assert.equal(n.version,'0.3');assert.deepEqual(n.assets,old.assets);});
test('variants and attachment tracks survive project roundtrip',()=>{const p=character(),v=addVariant(p,'eye','closed','闭眼');setAttachmentKey(p.clips[0],p.parts[0],.7,v);assert.deepEqual(parseProject(JSON.parse(JSON.stringify(p))),p);});
test('attachments use discrete steps, base before first key, null hides',()=>{const p=character(),v=addVariant(p,'eye','closed','闭眼');const c=p.clips[0];setAttachmentKey(c,p.parts[0],.7,v);setAttachmentKey(c,p.parts[0],1,null);assert.equal(sampleAttachment(c,'eye',.699),'base');assert.equal(sampleAttachment(c,'eye',.7),v);assert.equal(sampleAttachment(c,'eye',1),null);});
test('attachment timestamps overwrite and sort',()=>{const p=character(),v=addVariant(p,'eye','closed','闭眼'),c=p.clips[0];setAttachmentKey(c,p.parts[0],1,v);setAttachmentKey(c,p.parts[0],0,'base');setAttachmentKey(c,p.parts[0],1,null);assert.equal(c.attachments.eye.length,2);assert.equal(c.attachments.eye[1].variantId,null);});
test('blink is a four-frame clip and restores the open state at loop end',()=>{const p=character(),v=addVariant(p,'eye','closed','闭眼');blink(p,p.clips[0],'eye',v);assert.deepEqual(p.clips[0].attachments.eye.map(k=>k.variantId),['base',v,'base','base']);assert.equal(p.clips[0].attachments.eye.at(-1).time,2);});
test('variant alignment transforms are independent from texture dimensions',()=>{const p=character(),id=addVariant(p,'eye','closed','闭眼');const v=p.parts[0].variants[0];v.x=12;v.y=-4;v.scaleX=1.1;const a=variantPart(p,p.parts[0],id);assert.equal(a.asset.height,20);assert.equal(a.part.scaleX,-1.32);assert.notEqual(a.part.x,p.parts[0].x);});
test('moving pivot preserves all variant corners too',()=>{const p=character(),id=addVariant(p,'eye','closed','闭眼');p.parts[0].variants[0].x=9;let a=variantPart(p,p.parts[0],id);const before=partCorners(a.part,a.asset,worldBones(p));movePivot(p,'eye',.9,.1);a=variantPart(p,p.parts[0],id);const after=partCorners(a.part,a.asset,worldBones(p));before.forEach((v,i)=>{assert.ok(Math.abs(v.x-after[i].x)<1e-6);assert.ok(Math.abs(v.y-after[i].y)<1e-6);});});
test('unknown variants, duplicate ids, malformed tracks are rejected',()=>{for(const modify of [p=>p.parts[0].variants[0].assetId='absent',p=>p.parts[0].variants.push({...p.parts[0].variants[0]}),p=>p.clips[0].attachments={eye:[{time:0,variantId:'absent'}]},p=>p.clips[0].attachments={eye:[{time:3,variantId:'base'}]}]){const p=character();addVariant(p,'eye','closed','闭眼');modify(p);assert.throws(()=>parseProject(p));}});
test('undo snapshots do not share variant alignment or attachment keys',()=>{const p=character(),id=addVariant(p,'eye','closed','闭眼');blink(p,p.clips[0],'eye',id);const c=cloneProject(p);c.parts[0].variants[0].x=44;c.clips[0].attachments.eye[0].variantId=null;assert.equal(p.parts[0].variants[0].x,0);assert.equal(p.clips[0].attachments.eye[0].variantId,'base');});
test('Spine 3.8 slot attachment timeline references real exported skin entries',()=>{const p=character(),id=addVariant(p,'eye','closed','闭眼');blink(p,p.clips[0],'eye',id);const doc=exportSpine(p),slot=doc.animations.idle.slots.slot_eye.attachment;assert.equal(slot[1].name,`variant_${id}`);assert.equal(doc.skins[0].attachments.slot_eye[slot[1].name].path,'image_closed');assert.equal(usedAssets(p).length,2);assert.equal(doc.skins[0].attachments.slot_eye[slot[1].name].height,20);});
test('hidden slots stay hidden even if attachment animation is present',()=>{const p=character(),id=addVariant(p,'eye','closed','闭眼');p.parts.push({...p.parts[0],id:'visible'});p.parts[0].visible=false;blink(p,p.clips[0],'eye',id);assert.ok(exportSpine(p).animations.idle.slots.slot_eye.attachment.every(k=>k.name===null));});
test('chroma key pure green background yields actual zero alpha and zero RGB',()=>{const r=raster();rect(r,5,5,6,6);const out=keyRaster(r,options);assert.deepEqual([...out.data.slice(0,4)],[0,0,0,0]);assert.equal(out.data[(6*20+6)*4+3],255);assert.deepEqual(r.data.slice(0,4),new Uint8ClampedArray([0,255,0,255]));});
test('chroma algorithm is deterministic and supports magenta instead of green',()=>{const r=raster([255,0,255]);rect(r,7,7,6,6,[80,180,120]);const o={...options,color:[255,0,255]};assert.deepEqual(keyRaster(r,o),keyRaster(r,o));assert.equal(keyRaster(r,o).data[3],0);assert.equal(keyRaster(r,o).data[(8*20+8)*4+3],255);});
test('background report detects mismatched requested chroma and fake transparency',()=>{const r=raster();const v=backgroundReport(r,[255,0,255]);assert.equal(v.uniformity,1);assert.ok(v.warnings.length);r.data[3]=0;assert.equal(backgroundReport(r,[0,255,0]).opaque,false);});
test('same-color interior risk is correctable with explicit restoration brush',()=>{const r=raster();rect(r,3,3,14,14);rect(r,8,8,3,3,[0,255,0]);const out=keyRaster(r,options);assert.equal(out.data[(9*20+9)*4+3],0);brushMask(out,r,9,9,1,true);assert.equal(out.data[(9*20+9)*4+3],255);brushMask(out,r,9,9,1,false);assert.equal(out.data[(9*20+9)*4+3],0);});
test('separate islands propose multiple regions, a manual rectangle groups them',()=>{const r=raster();rect(r,2,3,3,3);rect(r,10,3,3,3);const out=keyRaster(r,options);assert.equal(componentRects(out).length,2);const grouped=cropRaster(out,{x:1,y:1,width:17,height:10},8);assert.equal(componentRects(grouped.image).length,2);assert.equal(grouped.bounds.width,11);assert.equal(alphaStats(grouped.image).touchesEdge,false);});
test('padding is newly transparent instead of copying adjacent sprites',()=>{const r=raster();rect(r,0,0,2,2);rect(r,3,0,2,2);const out=keyRaster(r,options),c=cropRaster(out,{x:0,y:0,width:2,height:2},8);assert.equal(c.image.width,18);assert.equal(alphaStats(c.image).foreground,4);assert.equal(alphaStats(c.image).touchesEdge,false);});
test('bad key thresholds, missing foreground and overlarge raster fail clearly',()=>{assert.throws(()=>keyRaster(raster(),{...options,outer:18}));assert.throws(()=>cropRaster(keyRaster(raster(),options),{x:0,y:0,width:20,height:20}));assert.throws(()=>componentRects({width:1e8,height:1,data:new Uint8ClampedArray()}));});
test('chroma recommendation avoids a green character palette',()=>{const r=raster([20,220,40]);assert.notDeepEqual(recommendColor(r),[0,255,0]);assert.deepEqual(hexRGB('#00FF00'),[0,255,0]);});
test('head plan has exactly 12 stable entries and merged purposes do not duplicate',()=>{assert.equal(specsFor(['head']).length,12);const s=specsFor(['head','idle']);assert.equal(s.length,new Set(s.map(v=>v.id)).size);});
test('every generated part prompt uses mandatory opaque chroma, no native-alpha route',()=>{const p=newPreparation();p.color='#ff00ff';const s=partsPrompt(p);assert.ok(s.includes('不透明的纯色 #ff00ff'));assert.ok(s.includes('不要透明背景'));assert.ok(s.includes('12 个部件'));assert.throws(()=>partsPrompt(p,[]));});
test('preparation serializer drops credentials and refuses external image sources',()=>{const p=newPreparation();p.apiKey='secret';assert.ok(!JSON.stringify(parsePreparation(p)).includes('secret'));p.characters=[{id:'a',name:'x',width:10,height:10,image:'https://evil.test/x',description:'',adopted:false,createdAt:''}];assert.throws(()=>parsePreparation(p));});
test('candidate approvals require a semantic name and reject duplicate confirmed versions',()=>{const p=newPreparation();const c={id:'a',semanticId:'',status:'review'};p.candidates=[c];assert.throws(()=>approveCandidate(p,'a'));c.semanticId='face_base';approveCandidate(p,'a');assert.equal(coverage(p).missing.length,11);p.candidates.push({...c,id:'b',status:'review'});assert.throws(()=>approveCandidate(p,'b'));assert.equal(c.status,'approved');});
test('editor importer strips unknown credentials at every serialized level',()=>{const p=character(),v=addVariant(p,'eye','closed','闭眼');blink(p,p.clips[0],'eye',v);p.apiKey='DO_NOT_EXPORT';p.canvas.key='DO_NOT_EXPORT';p.assets[0].token='DO_NOT_EXPORT';p.parts[0].variants[0].secret='DO_NOT_EXPORT';p.clips[0].attachments.eye[0].key='DO_NOT_EXPORT';assert.ok(!JSON.stringify(parseProject(p)).includes('DO_NOT_EXPORT'));});
test('same-hue dark screen remnants are removed without removing neutral white',()=>{const r=raster();rect(r,2,2,4,4,[0,150,0]);rect(r,12,12,3,3,[255,255,255]);const out=keyRaster(r,options);assert.equal(out.data[(3*20+3)*4+3],0);assert.equal(out.data[(13*20+13)*4+3],255);});
test('black anti-aliased edge is reconstructed instead of lost as dark green',()=>{const r=raster();rect(r,7,4,4,10,[0,0,0]);rect(r,6,4,1,10,[0,128,0]);const out=keyRaster(r,options),i=(8*20+6)*4;assert.ok(out.data[i+3]>100&&out.data[i+3]<155);assert.ok(out.data[i+1]<3);});
