import{useRef,useState}from'react';import{Download,Eye,EyeOff,FolderOpen,ImagePlus,Lock,RotateCcw,Save,Trash2,Unlock,Upload}from'lucide-react';

type Part={id:string;name:string;src:string;x:number;y:number;rotation:number;scale:number;z:number;visible:boolean;locked:boolean;pivotX:number;pivotY:number};
type Project={version:'0.1';name:string;canvas:{width:number;height:number};parts:Omit<Part,'src'>[]};
const uid=()=>crypto.randomUUID();

export default function App(){
 const[parts,setParts]=useState<Part[]>([]),[selected,setSelected]=useState<string|null>(null),[projectName,setProjectName]=useState('mage-character');
 const drag=useRef<{id:string;ox:number;oy:number}|null>(null);const canvasRef=useRef<HTMLDivElement>(null);
 const active=parts.find(p=>p.id===selected);
 const patch=(id:string,v:Partial<Part>)=>setParts(ps=>ps.map(p=>p.id===id?{...p,...v}:p));
 const addFiles=(files:FileList|null)=>{if(!files)return;[...files].filter(f=>f.type.startsWith('image/')).forEach((f,i)=>{const r=new FileReader();r.onload=()=>setParts(ps=>[...ps,{id:uid(),name:f.name.replace(/\.[^.]+$/,''),src:String(r.result),x:400+i*12,y:300+i*12,rotation:0,scale:1,z:ps.length,visible:true,locked:false,pivotX:.5,pivotY:.5}]);r.readAsDataURL(f)})};
 const pointerDown=(e:React.PointerEvent,p:Part)=>{e.stopPropagation();setSelected(p.id);if(p.locked)return;const rect=canvasRef.current!.getBoundingClientRect();drag.current={id:p.id,ox:e.clientX-rect.left-p.x,oy:e.clientY-rect.top-p.y};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};
 const pointerMove=(e:React.PointerEvent)=>{if(!drag.current)return;const rect=canvasRef.current!.getBoundingClientRect();patch(drag.current.id,{x:Math.round(e.clientX-rect.left-drag.current.ox),y:Math.round(e.clientY-rect.top-drag.current.oy)})};
 const pointerUp=()=>drag.current=null;
 const download=(name:string,text:string,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
 const saveProject=()=>{const data:Project={version:'0.1',name:projectName,canvas:{width:800,height:650},parts:parts.map(({src,...p})=>p)};download(projectName+'.project.json',JSON.stringify(data,null,2))};
 const exportScene=()=>{const payload={skeleton:{hash:'',spine:'ai-bone-studio-0.1',x:0,y:0,width:800,height:650,images:'./images/'},bones:[{name:'root'}],slots:parts.sort((a,b)=>a.z-b.z).map(p=>({name:p.name,bone:'root',attachment:p.name})),skins:[{name:'default',attachments:Object.fromEntries(parts.map(p=>[p.name,{[p.name]:{x:p.x-400,y:325-p.y,rotation:-p.rotation,scaleX:p.scale,scaleY:p.scale,width:0,height:0}}]))}],animations:{}};download(projectName+'.spine-draft.json',JSON.stringify(payload,null,2))};
 const reset=()=>{if(active)patch(active.id,{rotation:0,scale:1})};
 return <div className="app">
  <header><div className="brand"><span className="logo">A</span><div><b>AI Bone Studio</b><small>V0.1 · 角色拼装画板</small></div></div><input className="project-name" value={projectName} onChange={e=>setProjectName(e.target.value)}/><div className="top-actions"><label className="btn"><ImagePlus size={16}/>导入 PNG<input hidden multiple type="file" accept="image/*" onChange={e=>addFiles(e.target.files)}/></label><button className="btn" onClick={saveProject}><Save size={16}/>保存工程</button><button className="btn primary" onClick={exportScene}><Download size={16}/>导出 Spine 草稿</button></div></header>
  <aside className="left"><div className="panel-title">部件库 <span>{parts.length}</span></div>{parts.length===0?<label className="empty"><Upload/><b>导入拆图素材</b><small>支持 PNG / WebP，可一次选择多个文件</small><input hidden multiple type="file" accept="image/*" onChange={e=>addFiles(e.target.files)}/></label>:<div className="parts">{[...parts].sort((a,b)=>b.z-a.z).map(p=><div className={'part '+(selected===p.id?'on':'')} onClick={()=>setSelected(p.id)} key={p.id}><div className="thumb"><img src={p.src}/></div><span>{p.name}</span><button onClick={e=>{e.stopPropagation();patch(p.id,{visible:!p.visible})}}>{p.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button></div>)}</div>}</aside>
  <main className="workspace" onPointerMove={pointerMove} onPointerUp={pointerUp}><div className="hint">拖动零件完成角色初始化 · 点击零件后在右侧精调</div><div className="canvas" ref={canvasRef} onPointerDown={()=>setSelected(null)}>{[...parts].sort((a,b)=>a.z-b.z).map(p=>p.visible&&<img key={p.id} onPointerDown={e=>pointerDown(e,p)} draggable={false} className={'sprite '+(selected===p.id?'selected':'')} src={p.src} style={{left:p.x,top:p.y,zIndex:p.z,transformOrigin:`${p.pivotX*100}% ${p.pivotY*100}%`,transform:`translate(-${p.pivotX*100}%,-${p.pivotY*100}%) rotate(${p.rotation}deg) scale(${p.scale})`,pointerEvents:p.locked?'none':'auto'}}/>)}</div></main>
  <aside className="right"><div className="panel-title">属性</div>{!active?<div className="no-selection">选择画布中的一个部件</div>:<div className="props"><div className="active-name">{active.name}</div><div className="row"><label>X<input type="number" value={active.x} onChange={e=>patch(active.id,{x:+e.target.value})}/></label><label>Y<input type="number" value={active.y} onChange={e=>patch(active.id,{y:+e.target.value})}/></label></div><label>旋转 <b>{active.rotation}°</b><input type="range" min="-180" max="180" value={active.rotation} onChange={e=>patch(active.id,{rotation:+e.target.value})}/></label><label>缩放 <b>{active.scale.toFixed(2)}</b><input type="range" min="0.1" max="3" step="0.01" value={active.scale} onChange={e=>patch(active.id,{scale:+e.target.value})}/></label><label>层级 Z<input type="number" value={active.z} onChange={e=>patch(active.id,{z:+e.target.value})}/></label><div className="row"><label>Pivot X<input type="number" min="0" max="1" step=".05" value={active.pivotX} onChange={e=>patch(active.id,{pivotX:+e.target.value})}/></label><label>Pivot Y<input type="number" min="0" max="1" step=".05" value={active.pivotY} onChange={e=>patch(active.id,{pivotY:+e.target.value})}/></label></div><div className="prop-buttons"><button onClick={()=>patch(active.id,{locked:!active.locked})}>{active.locked?<Unlock size={15}/>:<Lock size={15}/>} {active.locked?'解锁':'锁定'}</button><button onClick={reset}><RotateCcw size={15}/>重置</button><button className="danger" onClick={()=>{setParts(ps=>ps.filter(p=>p.id!==active.id));setSelected(null)}}><Trash2 size={15}/>删除</button></div></div>}</aside>
  <footer><span>V0.1 拼装模式</span><span>下一阶段：骨骼 · 关键帧 · 动画时间轴</span></footer>
 </div>
}