import { type Asset, uid } from './model.js';
import { type Raster, type Rect, type KeyOptions, keyRaster, hexRGB, rgbHex, backgroundReport, recommendColor, componentRects, cropRaster, brushMask, alphaStats, KEY_VERSION } from './chroma.js';
import { type Preparation, type Candidate, type Purpose, type JobRef, newPreparation, parsePreparation, specsFor, partsPrompt, characterPrompt, addCharacter, approveCandidate, coverage } from './production.js';
import { writeZip, textEntry } from './zip.js';
import { download } from './io.js';
const esc=(v:unknown):string=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const $=<T extends HTMLElement=HTMLElement>(id:string):T=>document.getElementById(id) as T;
const waitPaint=():Promise<void>=>new Promise(resolve=>requestAnimationFrame(()=>resolve()));
function rasterURL(r:Raster):string{const c=document.createElement('canvas');c.width=r.width;c.height=r.height;c.getContext('2d')!.putImageData(new ImageData(new Uint8ClampedArray(r.data),r.width,r.height),0,0);return c.toDataURL('image/png');}
async function rasterFrom(url:string):Promise<Raster>{return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{if(image.width*image.height>16777216){reject(new Error('图片超过 1600 万像素。'));return;}const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(image,0,0);resolve({width:canvas.width,height:canvas.height,data:ctx.getImageData(0,0,canvas.width,canvas.height).data});};image.onerror=()=>reject(new Error('图片无法解码。'));image.src=url;});}
async function fileRaster(file:Blob):Promise<Raster>{if(file.size>20*1024*1024)throw new Error('图片超过 20MB。');const url=URL.createObjectURL(file);try{return await rasterFrom(url);}finally{URL.revokeObjectURL(url);}}
async function stored(write?:Preparation):Promise<Preparation|null>{return new Promise((resolve,reject)=>{const request=indexedDB.open('ai-bone-preparation',1);request.onupgradeneeded=()=>request.result.createObjectStore('state');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('state',write?'readwrite':'readonly'),op=write?tx.objectStore('state').put(write,'latest'):tx.objectStore('state').get('latest');let result:Preparation|null=null;op.onsuccess=()=>{if(!write&&op.result)try{result=parsePreparation(op.result);}catch(e){reject(e);}};tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(tx.error);};};});}
interface Provider {id:string; label:string; model:string; generate:boolean; edit:boolean}
interface RemoteJob {id:string; requestId:string; kind:'character'|'parts'; status:string; createdAt:string; error?:string; images?:{dataUrl:string}[];usage?:unknown}
function checkedRemoteJob(value:unknown):RemoteJob {
 const j=value as RemoteJob;if(!j||typeof j.id!=='string'||! /^[a-zA-Z0-9_-]{8,80}$/.test(j.id)||typeof j.requestId!=='string'||! /^[a-zA-Z0-9_-]{8,80}$/.test(j.requestId)||!['character','parts'].includes(j.kind)||!['queued','running','succeeded','failed','unknown'].includes(j.status)||typeof j.createdAt!=='string'||j.createdAt.length>100||j.error&&typeof j.error!=='string')throw new Error('网关任务元数据格式不安全或不兼容。');return j;
}
export function initPreparation(hooks:{importAssets:(assets:Asset[])=>Promise<void>; notice:(s:string,error?:boolean)=>void}):{open:()=>void} {
 let state=newPreparation(),step=0,processing=false,report='',original:Raster|null=null,keyed:Raster|null=null,rects:Rect[]=[],maskUndo:Uint8ClampedArray[]=[],maskEdited=false;
 let boxStart:{x:number;y:number}|null=null,box:Rect|null=null,brushStart=false,apiURL='',access='',providers:Provider[]=[],providerId='',taskMessage='',lastJobs:RemoteJob[]=[];
 let saveTimer=0,modified=false,keyOptions:KeyOptions={color:[0,255,0],inner:18,outer:95,despill:true};
 const root=document.createElement('dialog');root.id='preparation';root.className='prep';document.body.append(root);
 try{apiURL=localStorage.getItem('bone-gateway-url')??'';}catch{}
 const activeCharacter=()=>state.characters.find(v=>v.id===state.activeCharacter), activeSheet=()=>state.sheets.find(v=>v.id===state.activeSheet);
 function save():void{modified=true;clearTimeout(saveTimer);saveTimer=window.setTimeout(()=>{try{const safe=parsePreparation(state);void stored(safe).catch(()=>hooks.notice('准备流程本地保存失败，请下载“准备工程”备份。',true));}catch(e){hooks.notice((e as Error).message,true);}},450);}
 async function run(work:()=>Promise<void>):Promise<void>{if(processing)return;modified=true;processing=true;root.classList.add('processing');const msg=$('prep-status');if(msg)msg.textContent='正在处理…';await waitPaint();try{await work();save();}catch(e){hooks.notice((e as Error).message,true);report=(e as Error).message;}finally{processing=false;root.classList.remove('processing');render();}}
 function render():void{
  const role=activeCharacter(),sheet=activeSheet(),qa=coverage(state);
  root.innerHTML=`<div class="prep-header"><div><span class="eyebrow">AI BONE STUDIO / 0.3 BETA</span><h2>从一个想法，到一个会动的角色。</h2></div><button data-action="close">返回拼装画板 ↗</button></div>
  <nav class="prep-steps">${['准备角色','选择用途','拆件检查台','服务与任务'].map((s,i)=>`<button data-step="${i}" class="${i===step?'active':''}"><b>0${i+1}</b>${s}</button>`).join('')}</nav>
  <div class="prep-body">${step===0?`<div class="prep-grid"><section><h3>01 / 准备你的角色</h3><p>可以描述生成，也可以上传已有原画。已有透明部件？直接返回画板导入，不需要配置 API。</p><label>角色名称<input id="prep-name" value="${esc(state.name)}" maxlength="100"></label><label>描述与需求<textarea id="prep-description" rows="5" maxlength="10000">${esc(state.description)}</textarea></label><div class="prep-actions"><input id="prep-amend" placeholder="追加修改，如：帽子更简单，不带法杖" maxlength="1000"><button data-action="amend">加入需求</button></div><p class="micro">需求整理使用固定模板，不会因为输入文字而产生费用。</p>${role?'<label><span><input type="checkbox" id="role-reference"> 参考当前版本修改（图生图，不覆盖旧图）</span></label>':''}<div class="prep-actions"><button class="primary" data-action="generate-role">生成角色（需服务）</button><label class="button-label">上传角色<input id="prep-role-file" type="file" accept="image/png,image/jpeg,image/webp" hidden></label></div><details><summary>查看可复制的角色提示词</summary><textarea readonly rows="5">${esc(characterPrompt(state))}</textarea></details><div class="help-card">这一步可以跳过。原画仅保存在本地；点击生成并确认后，选定图片与提示词才会发送给你配置的服务。</div></section>
  <section><h3>角色版本 <small>${state.characters.length} / 20</small></h3>${role?`<div class="role-preview"><img src="${role.image}" alt="当前角色原画"></div><div class="prep-actions"><button data-action="adopt" class="primary">${role.adopted?'✓ 已采用此版本':'采用此版本'}</button><button data-step="1">下一步 →</button></div><p class="micro">不会覆盖原画。后续修改和选定视图另存为新版本。</p><details><summary>设计稿含多个视图？裁出本次使用的角色</summary><div class="prep-four">${['x','y','width','height'].map((id,i)=>`<label>${['左侧 X','顶部 Y','宽度','高度'][i]}<input id="crop-${id}" type="number" value="${i<2?0:i===2?role.width:role.height}" min="0"></label>`).join('')}</div><button data-action="crop-role">裁选为新版本（像素坐标）</button></details><div class="versions">${state.characters.map((v,i)=>`<button data-role="${v.id}" class="${v.id===state.activeCharacter?'active':''}">V${i+1} ${esc(v.name)}${v.adopted?' ✓':''}</button>`).join('')}</div>`:'<div class="prep-empty">先上传一张角色原画，或配置生成服务。<br>不用三视图也可以开始。</div>'}<button data-action="role-to-sheet" ${role?'':'disabled'}>我上传的已经是纯色部件图 → 检查台</button></section></div>`:''}
  ${step===1?`<div class="prep-grid"><section><h3>02 / 动作决定怎么拆</h3><label>本次角色视图<select id="prep-view">${['正面','侧面','四分之三侧面','背面'].map(v=>`<option ${v===state.view?'selected':''}>${v}</option>`).join('')}</select></label><div class="purpose-options">${[['head','头像与表情','独立五官、睁闭眼、嘴型'],['idle','全身待机','加上躯干、手臂、裙摆和腿'],['game','基础游戏动作规划','共用一套素材；七动作仍待逐项实现']].map(([id,label,help])=>`<label><input type="checkbox" data-purpose="${id}" ${state.purposes.includes(id as Purpose)?'checked':''}><b>${label}</b><small>${help}</small></label>`).join('')}</div><div class="warning">正面图不能自动变成自然的侧面跑步。第一阶段重点是头像与表情；全身清单可编辑，但七个完整动作模板未在本版交付。</div><label>本批次纯色背景<input type="color" id="prep-color" value="${state.color}"></label><button data-action="recommend" ${role?'':'disabled'}>按原画配色建议背景色</button><p class="micro">固定“纯色生成 → 程序抠图”。没有模型原生透明选项。建议色仍需要检查是否与角色局部撞色。</p><button data-step="2" class="primary">进入拆件检查台 →</button></section><section><h3>部件清单 <small>${state.specs.length} 项</small></h3><div class="specs">${state.specs.map(s=>`<div><span><b>${esc(s.label)}</b><small>${esc(s.id)} / ${esc(s.group)}</small></span><button data-remove-spec="${s.id}" title="不需要此部件">×</button></div>`).join('')}</div><div class="prep-actions"><input id="custom-spec" placeholder="新增部件名称，如：张嘴"><button data-action="add-spec">新增</button><button data-action="reset-specs">恢复预设清单</button></div><p class="micro">删除清单项不删除旧图片；已确认素材会保留，便于返回修复。L/R 指角色自身左右。</p></section></div>`:''}
  ${step===2?`<div class="prep-work"><section class="sheet-panel"><h3>03 / 先抠除背景，再确认部件</h3><div class="prep-actions"><label class="button-label primary">上传纯色部件图<input id="prep-sheet-file" type="file" accept="image/png,image/jpeg,image/webp" hidden></label><button data-action="demo-sheet">试用练习拆件图</button></div><div class="prep-actions"><select id="generate-group"><option value="all">生成全部清单</option>${[...new Set(state.specs.map(s=>s.group))].map(g=>`<option value="group:${esc(g)}">只生成：${esc(g)}</option>`).join('')}${state.specs.map(s=>`<option value="part:${s.id}">仅重做：${esc(s.label)}</option>`).join('')}</select><button data-action="generate-parts">参考角色生成（需服务）</button></div><details><summary>复制拆件提示词，在其他工具中生图</summary><textarea id="parts-prompt" readonly rows="6">${esc(state.specs.length?partsPrompt(state):'先添加部件清单。')}</textarea><button data-action="copy-prompt">复制提示词</button></details>
  ${sheet?`<select id="sheet-select">${state.sheets.map((s,i)=>`<option value="${s.id}" ${s.id===sheet.id?'selected':''}>${i+1}. ${esc(s.name)}</option>`).join('')}</select><div class="key-controls"><label>抠图背景色<input type="color" id="key-color" value="${rgbHex(keyOptions.color)}"></label><label>去除容差<input id="key-inner" type="number" min="0" max="180" value="${keyOptions.inner}"></label><label>边缘过渡<input id="key-outer" type="number" min="1" max="250" value="${keyOptions.outer}"></label><label><input type="checkbox" id="key-despill" ${keyOptions.despill?'checked':''}>边缘去色</label></div><div class="prep-actions"><button data-action="measure">采用实测背景色</button><button data-action="key" class="primary">重新抠图</button></div><p class="micro">仅改变当前预览，已确认的候选不会被覆盖；重新抠图会清空当前画笔修改。</p><div class="prep-actions"><select id="mask-tool"><option value="box">框选零件 / 拆开粘连</option><option value="erase">擦除蒙版</option><option value="restore">恢复原始像素</option></select><label class="compact">笔刷<input id="brush-radius" type="number" min="1" max="80" value="10"></label><button data-action="mask-undo">撤销画笔</button><select id="inspect-bg"><option value="checker">检查网格</option><option value="white">白底</option><option value="dark">深色底</option><option value="original">原始纯色图</option></select></div><div id="mask-wrap" class="mask-wrap checker"><canvas id="mask-canvas" aria-label="抠图和框选画板"></canvas></div><div class="prep-actions"><button data-action="crop-box">将框选加入候选</button><button data-action="detect">自动检测候选区域</button></div><details><summary>规则网格切分（保留同一格内的分离像素）</summary><div class="prep-actions"><label>列<input id="grid-cols" type="number" min="1" max="12" value="3"></label><label>行<input id="grid-rows" type="number" min="1" max="12" value="4"></label><button data-action="grid">按网格加入候选</button></div></details><p class="micro">框选可把同一零件的睫毛、高光一起圈入，也可以将粘连件分开。画笔修改只保留在本次预览；裁出候选会保存修正结果，原图始终保留。</p>`:'<div class="prep-empty">纯色图在这里抠图。已有独立透明 PNG？返回画板直接导入，不需要再加背景。</div>'}</section>
  <section class="candidate-panel"><h3>检查与归组 <small>已确认 ${qa.approved} / ${state.specs.length}</small></h3><p class="micro">自动区域≠语义部件。逐个指定名称并看白底/深底，再确认。勾选几个候选可以合成一件。</p><div class="candidate-grid">${state.candidates.filter(c=>c.status!=='archived').map(c=>`<article data-candidate="${c.id}" class="candidate ${c.status}"><label class="candidate-check"><input type="checkbox" data-select-candidate="${c.id}">归组</label><div class="candidate-image checker"><img src="${c.image}" alt="${esc(c.name)}"></div><select data-semantic="${c.id}"><option value="">请选择部件名称</option>${state.specs.map(s=>`<option value="${s.id}" ${s.id===c.semanticId?'selected':''}>${esc(s.label)}</option>`).join('')}</select><small>${c.width}×${c.height} · ${c.status==='approved'?'✓ 已确认':c.status==='repair'?'需修复':'待确认'}${c.imported?' · 已送入画板':''}</small>${c.warnings.length?`<small class="warn">${esc(c.warnings.join(' '))}</small>`:''}<div class="prep-actions"><button data-approve="${c.id}">${c.status==='approved'?'撤回确认':'确认可用'}</button><button data-archive="${c.id}">归档</button></div></article>`).join('')}</div><div class="prep-actions"><button data-action="merge">合并勾选候选</button><button data-action="unarchive">恢复最近归档</button><button data-action="mark-repair">勾选项标需修复</button></div><div class="warning">缺少：${qa.missing.length?esc(qa.missing.map(s=>s.label).join('、')):'没有缺项'}${qa.duplicates.length?`；重复：${esc(qa.duplicates.join(','))}`:''}</div><div class="prep-actions"><button data-action="send-parts" class="primary" ${qa.approved?'':'disabled'}>已确认部件 → 拼装画板</button><button data-action="download-parts" ${qa.approved?'':'disabled'}>下载透明部件 ZIP</button></div><p class="micro">不会依据素材板坐标假装自动拼成人物。清单不完整时可以确认后导入部分素材；缺项保留提醒。</p></section></div>`:''}
  ${step===3?`<div class="prep-grid"><section><h3>连接你的生图服务</h3><p>公开 GitHub Pages 仅托管网页，不能存储供应商密钥或运行生成任务。未连接服务时，其他本地功能仍可使用。</p><label>安全网关地址<input id="gateway-url" type="url" placeholder="https://你的网关域名" value="${esc(apiURL)}" autocomplete="off"></label><label>服务访问口令（不是 OpenAI / Gemini API Key）<input id="gateway-token" type="password" placeholder="由服务管理员提供；仅保存在当前页面内存" autocomplete="off" value="${esc(access)}"></label><div class="prep-actions"><button data-action="connect" class="primary">连接服务（不触发生图）</button><button data-action="disconnect">退出服务</button></div><p class="micro">连接只检查我们的网关配置，不代表供应商接口已完成付费验证。API Key 和上游地址由管理员在后端环境配置；不写入 GitHub 或工程。</p><label>选择图片服务<select id="provider">${providers.length?providers.map(p=>`<option value="${esc(p.id)}" ${p.id===providerId?'selected':''}>${esc(p.label)} / ${esc(p.model)}</option>`).join(''):'<option>尚未连接</option>'}</select></label><p>${esc(taskMessage)}</p><div class="warning">生成和测试都可能收费。费用目前显示“未知”，由供应商实际账单确认。提交前会再次确认；不会因刷新或网络错误自动重试。部件始终使用不透明纯色背景。</div><p class="micro">后端代码在 apps/gateway。按其 README 部署并配置密钥后，填写网关地址即可。本次站点不假装已经配置收费服务。</p></section><section><h3>可恢复的生成任务</h3><button data-action="refresh-jobs">刷新任务列表</button><p class="micro">刷新只查询，不发起新的付费生成。重新打开网页需再次输入服务访问口令。默认服务端保留 7 天，可手动删除输入和结果；本地版本不会一起删除。</p><div class="task-list">${lastJobs.map(j=>`<article><b>${j.kind==='parts'?'部件生成':'角色生成'}</b><span>${esc(j.status)} · ${esc(j.id.slice(0,10))}</span>${j.error?`<p>${esc(j.error)}</p>`:''}<div class="prep-actions"><button data-job-use="${j.id}" ${j.status==='succeeded'?'':'disabled'}>取回到准备流程</button><button data-job-delete="${j.id}" ${['queued','running'].includes(j.status)?'disabled':''}>删除服务端记录</button></div></article>`).join('')||'<div class="prep-empty">没有读取到任务。连接服务后可以恢复已提交任务。</div>'}</div></section></div>`:''}
  </div><footer class="prep-footer"><span id="prep-status" role="status">${esc(report||'本地准备流程 · 无 API 也可使用 · 每个阶段都可跳过')}</span><div class="prep-actions"><button data-action="save-prep">保存准备工程</button><label class="button-label">打开准备工程<input id="prep-open" type="file" accept=".json" hidden></label><button data-action="clear-prep">清空本地准备</button></div></footer>`;
  if(step===2&&sheet) {drawMask();bindMask();}
 }
 function drawMask():void{const c=$<HTMLCanvasElement>('mask-canvas');if(!c||!keyed)return;const bg=$<HTMLSelectElement>('inspect-bg')?.value??'checker';const r=bg==='original'?original!:keyed;c.width=r.width;c.height=r.height;const ctx=c.getContext('2d')!;ctx.putImageData(new ImageData(new Uint8ClampedArray(r.data),r.width,r.height),0,0);
  ctx.strokeStyle='#ee813e';ctx.lineWidth=Math.max(2,r.width/400);for(const b of rects)ctx.strokeRect(b.x,b.y,b.width,b.height);if(box){ctx.strokeStyle='#6e36fa';ctx.strokeRect(box.x,box.y,box.width,box.height);}}
 function bindMask():void{const c=$<HTMLCanvasElement>('mask-canvas');if(!c)return;
  const at=(e:PointerEvent)=>{const b=c.getBoundingClientRect();return {x:(e.clientX-b.left)*c.width/b.width,y:(e.clientY-b.top)*c.height/b.height};};
  const paint=(e:PointerEvent)=>{if(!keyed||!original)return;const p=at(e);brushMask(keyed,original,p.x,p.y,Number($<HTMLInputElement>('brush-radius').value)||10,$<HTMLSelectElement>('mask-tool').value==='restore');maskEdited=true;drawMask();};
  c.onpointerdown=e=>{if(processing||!keyed)return;e.preventDefault();c.setPointerCapture(e.pointerId);const tool=$<HTMLSelectElement>('mask-tool').value;if(tool==='box'){boxStart=at(e);box=null;rects=[];}else{maskUndo.push(new Uint8ClampedArray(keyed.data));if(maskUndo.length>4)maskUndo.shift();brushStart=true;paint(e);}};
  c.onpointermove=e=>{if(brushStart){paint(e);return;}if(boxStart){const p=at(e);box={x:Math.min(p.x,boxStart.x),y:Math.min(p.y,boxStart.y),width:Math.abs(p.x-boxStart.x),height:Math.abs(p.y-boxStart.y)};drawMask();}};
  c.onpointerup=()=>{brushStart=false;boxStart=null;};c.onpointercancel=()=>{brushStart=false;boxStart=null;};
 }
 async function loadSheet():Promise<void>{original=keyed=null;rects=[];box=null;maskUndo=[];maskEdited=false;const s=activeSheet();if(!s)return;original=await rasterFrom(s.image);if(original.width*original.height>4194304)throw new Error('首版手机抠图限制 400 万像素，请先裁图或缩小到 2048×2048 以内。');keyOptions={...keyOptions,color:hexRGB(s.color)};await rekey();}
 async function rekey():Promise<void>{if(!original)return;const check=backgroundReport(original,keyOptions.color);if(!check.opaque)throw new Error('这张图带透明边框。已抠好的透明零件请返回画板直接导入；AI 拆件请提供纯色原图。');keyed=keyRaster(original,keyOptions);maskEdited=false;maskUndo=[];rects=[];box=null;const stats=alphaStats(keyed);report=`背景一致度 ${Math.round(check.uniformity*100)}%，前景 ${stats.foreground} 像素。${check.warnings.join(' ')} ${stats.transparent===0?'未去除背景，请检查色值！':''}`;}
 async function newSheet(r:Raster,name:string,roleId=state.activeCharacter):Promise<void>{if(r.width*r.height>4194304)throw new Error('首版抠图限制 400 万像素，请先缩小到 2048×2048 以内。');if(state.sheets.length>=30)throw new Error('最多 30 张部件源图，请保存并新建准备工程。');const id=uid('sheet');state.sheets.push({id,name:name.slice(0,120),image:rasterURL(r),width:r.width,height:r.height,color:state.color,roleId,createdAt:new Date().toISOString()});state.activeSheet=id;step=2;await loadSheet();}
 function candidateFrom(rect:Rect):Candidate {if(!keyed||!activeSheet())throw new Error('先上传部件图并抠图。');if(state.candidates.length>=256)throw new Error('候选最多 256 项。');const cut=cropRaster(keyed,rect),stats=alphaStats(cut.image);return {id:uid('candidate'),name:'未命名候选',semanticId:'',sheetId:state.activeSheet!,image:rasterURL(cut.image),width:cut.image.width,height:cut.image.height,bounds:cut.bounds,status:'review',key:{...keyOptions,color:[...keyOptions.color]},keyVersion:KEY_VERSION,warnings:[...(stats.foreground<8?['前景很少，请复核']:[]),...(original?backgroundReport(original,keyOptions.color).warnings:[])],imported:false,maskEdited};}
 const checkedIDs=():string[]=>[...root.querySelectorAll<HTMLInputElement>('[data-select-candidate]:checked')].map(e=>e.dataset.selectCandidate!);
 async function api(path:string,method='GET',body?:unknown):Promise<unknown>{const url=new URL(apiURL);if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))throw new Error('服务必须使用 HTTPS（本机开发除外）。');if(url.username||url.password||url.search||url.hash)throw new Error('网关地址不能包含账号、查询参数或片段。');if(!access)throw new Error('先输入服务访问口令。');
  const response=await fetch(`${apiURL.replace(/\/$/,'')}${path}`,{method,headers:{'Authorization':`Bearer ${access}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000),redirect:'error'});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error??`服务返回 ${response.status}`);return payload;}
 async function refreshJobs():Promise<void>{const result=await api('/jobs') as {jobs:RemoteJob[]};if(!Array.isArray(result.jobs))throw new Error('任务响应格式不兼容。');if(result.jobs.length>200)throw new Error('服务返回过多任务。');lastJobs=result.jobs.map(checkedRemoteJob);for(const j of lastJobs){const ref=state.jobs.find(v=>v.id===j.id);if(ref)ref.status=j.status;}taskMessage=`已连接，找到 ${lastJobs.length} 个服务端任务。`;}
 async function generate(kind:'character'|'parts'):Promise<void>{const provider=providers.find(v=>v.id===providerId);if(!provider){step=3;report='先连接安全网关；也可以复制提示词，在其他生图工具生成后上传。';return;}
  const role=activeCharacter(),editing=kind==='parts'||!!$<HTMLInputElement>('role-reference')?.checked;if(kind==='parts'&&(!role||!role.adopted))throw new Error('先在“准备角色”中采用一个原画版本。');if(!(editing?provider.edit:provider.generate))throw new Error('这个服务未配置对应的图片生成/编辑能力，不会退化成其他请求。');
  const group=$<HTMLSelectElement>('generate-group')?.value??'all',ids=state.specs.filter(s=>group==='all'||group===`group:${s.group}`||group===`part:${s.id}`).map(s=>s.id);
  const prompt=kind==='character'?characterPrompt(state):partsPrompt(state,ids);
  if(!confirm(`将向 ${provider.label} / ${provider.model} 发送${editing?'选定角色图片与':''}提示词，生成一张${kind==='parts'?'纯色部件图':'角色图'}。费用未知，供应商可能计费。是否提交一次？`))return;
  const requestId=uid('request'),ref:JobRef={id:requestId,requestId,kind,provider:provider.id,roleId:editing?role?.id??null:null,specIds:ids,color:state.color,imported:false,status:'submitting',createdAt:new Date().toISOString()};
  state.jobs.push(ref);await stored(parsePreparation(state));
  try{const result=await api('/jobs','POST',{requestId,kind,provider:provider.id,prompt,reference:editing?role!.image:undefined,color:state.color,confirmed:true}) as {job:RemoteJob};checkedRemoteJob(result.job);if(result.job.id!==requestId)throw new Error('服务返回的任务编号不匹配。');ref.id=result.job.id;ref.status=result.job.status;report='任务已提交。可以切后台；到“服务与任务”刷新查询，不会重复生成。';}
  catch(e){ref.status='unknown';report='提交结果未知：请在服务任务列表查询，不要直接再次点击生成。';hooks.notice(report,true);}
  step=3;await refreshJobs().catch(()=>{});
 }
 async function useJob(id:string):Promise<void>{const j=checkedRemoteJob(await api(`/jobs/${encodeURIComponent(id)}`));const ref=state.jobs.find(v=>v.id===id||v.requestId===j.requestId);
  if(ref?.imported&&!confirm('这个任务已经取回过。再复制一份？不会再调用生图。'))return;
  if(j.status!=='succeeded'||!j.images?.length)throw new Error('任务尚未成功或没有返回图片。');
  if(j.kind==='parts'&&!ref)throw new Error('本地没有此部件任务的角色和背景记录。请先打开当时的准备工程，再取回，避免错误关联。');
  for(const result of j.images){if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(result.dataUrl)||result.dataUrl.length>30*1024*1024)throw new Error('服务图片格式不安全或过大。');const r=await rasterFrom(result.dataUrl);
   if(j.kind==='character'){addCharacter(state,rasterURL(r),r.width,r.height,'生成角色',ref?.roleId??undefined);step=0;}
   else{const previous=state.color;state.color=ref!.color;try{await newSheet(r,'生成部件图',ref!.roleId);}finally{state.color=previous;}}
  }if(ref)ref.imported=true;report='结果已取回。生成结果仍需检查，未自动标记为可用。';}
 async function demoSheet():Promise<void>{const canvas=document.createElement('canvas');canvas.width=900;canvas.height=900;const c=canvas.getContext('2d')!;c.fillStyle='#00ff00';c.fillRect(0,0,900,900);
  for(let i=0;i<12;i++){const x=(i%3)*300+150,y=Math.floor(i/3)*225+112;c.save();c.translate(x,y);c.fillStyle='#ccb9f1';c.strokeStyle='#513461';c.lineWidth=6;
    if(i===0){c.fillStyle='#ffdfd2';c.beginPath();c.ellipse(0,0,82,89,0,0,Math.PI*2);c.fill();c.stroke();}
    else if(i<5){c.beginPath();c.roundRect(-90,-65,180,i===1?150:100,40);c.fill();c.stroke();}
    else if(i<7){c.beginPath();c.moveTo(-45,5);c.quadraticCurveTo(0,-20,45,2);c.stroke();}
    else if(i<9){c.fillStyle='#684593';c.beginPath();c.ellipse(0,0,27,40,0,0,Math.PI*2);c.fill();c.fillStyle='white';c.beginPath();c.arc(-8,-15,8,0,Math.PI*2);c.fill();}
    else{c.beginPath();c.moveTo(-40,-5);c.quadraticCurveTo(0,25,40,-5);c.stroke();}c.restore();}
  state.color='#00ff00';state.specs=specsFor(['head']);await newSheet({width:900,height:900,data:c.getImageData(0,0,900,900).data},'本地几何练习图（不是 AI 生成）',null);report='练习图为 3 列×4 行，可试用网格切分与逐件确认。';}
 root.addEventListener('click',e=>{const t=e.target as HTMLElement,b=t.closest<HTMLElement>('button');if(!b||processing)return;const stepValue=b.dataset.step;if(stepValue!==undefined){step=Number(stepValue);render();return;}
  if(b.dataset.role){state.activeCharacter=b.dataset.role;save();render();return;}
  if(b.dataset.removeSpec){if(state.specs.length<=1){hooks.notice('至少保留一个部件清单项。',true);return;}state.specs=state.specs.filter(s=>s.id!==b.dataset.removeSpec);save();render();return;}
  void run(async()=>{
   if(b.dataset.approve){const c=state.candidates.find(c=>c.id===b.dataset.approve)!;if(c.status==='approved')c.status='review';else{if(c.warnings.length&&!confirm('该候选存在提醒。请确认已检查白底、深色底和轮廓后继续。'))return;approveCandidate(state,c.id);}return;}
   if(b.dataset.archive){const c=state.candidates.find(c=>c.id===b.dataset.archive)!;c.status='archived';return;}
   if(b.dataset.jobUse){await useJob(b.dataset.jobUse);return;}
   if(b.dataset.jobDelete){if(confirm('删除这个服务端任务的输入和结果？已取回的本地图片保留。')){await api(`/jobs/${b.dataset.jobDelete}`,'DELETE');await refreshJobs();}return;}
   switch(b.dataset.action){
    case 'close':root.close();break;
    case 'amend':{const v=$<HTMLInputElement>('prep-amend').value.trim();if(v)state.description+='\n调整：'+v;break;}
    case 'adopt':{const v=activeCharacter();if(v){v.adopted=true;report='已采用当前版本，其他原图保留。';}break;}
    case 'crop-role':{const role=activeCharacter();if(!role)break;const r=await rasterFrom(role.image);const nums=['x','y','width','height'].map(k=>Number($<HTMLInputElement>(`crop-${k}`).value));const [x,y,w,h]=nums;if(!nums.every(Number.isFinite)||x<0||y<0||w<1||h<1||x+w>r.width||y+h>r.height)throw new Error('裁选范围超出原图。');const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const image=await rasterFrom(role.image);const full=document.createElement('canvas');full.width=r.width;full.height=r.height;full.getContext('2d')!.putImageData(new ImageData(image.data,image.width,image.height),0,0);canvas.getContext('2d')!.drawImage(full,x,y,w,h,0,0,w,h);addCharacter(state,canvas.toDataURL(),canvas.width,canvas.height,role.name+' / 裁选',role.id);break;}
    case 'role-to-sheet':{const role=activeCharacter();if(role)await newSheet(await rasterFrom(role.image),'从上传图进入拆件');break;}
    case 'recommend':{const v=activeCharacter();if(v){state.color=rgbHex(recommendColor(await rasterFrom(v.image)));report='已建议背景色；请仍检查角色是否有相同颜色。';}break;}
    case 'reset-specs':state.specs=specsFor(state.purposes);break;
    case 'add-spec':{const name=$<HTMLInputElement>('custom-spec').value.trim();if(name)state.specs.push({id:uid('custom'),label:name.slice(0,120),group:'自定义',instruction:'独立部件，补全动画需要的隐藏区域'});break;}
    case 'generate-role':await generate('character');break;
    case 'generate-parts':await generate('parts');break;
    case 'copy-prompt':await navigator.clipboard.writeText(partsPrompt(state));report='提示词已复制，可在其他生图工具中使用。';break;
    case 'demo-sheet':await demoSheet();break;
    case 'measure':if(original)keyOptions.color=backgroundReport(original,keyOptions.color).measured;await rekey();break;
    case 'key':{keyOptions={color:hexRGB($<HTMLInputElement>('key-color').value),inner:Number($<HTMLInputElement>('key-inner').value),outer:Number($<HTMLInputElement>('key-outer').value),despill:$<HTMLInputElement>('key-despill').checked};await rekey();break;}
    case 'mask-undo':if(keyed&&maskUndo.length)keyed.data=maskUndo.pop()!;break;
    case 'crop-box':if(!box||box.width<1||box.height<1)throw new Error('先在预览上拖出一个矩形。');state.candidates.push(candidateFrom(box));box=null;break;
    case 'detect':if(keyed){rects=componentRects(keyed);if(!confirm(`检测到 ${rects.length} 个连通区域（不等于部件数量）。加入待确认候选？细小睫毛可稍后合并。`))break;for(const r of rects)state.candidates.push(candidateFrom(r));report=`已加入 ${rects.length} 个候选，没有自动认定合格。`;}break;
    case 'grid':{if(!keyed)break;const cols=Number($<HTMLInputElement>('grid-cols').value),rows=Number($<HTMLInputElement>('grid-rows').value);if(!Number.isInteger(cols)||!Number.isInteger(rows)||cols<1||rows<1||cols*rows>100)throw new Error('网格数量无效。');for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){try{const c=candidateFrom({x:Math.floor(x*keyed.width/cols),y:Math.floor(y*keyed.height/rows),width:Math.floor((x+1)*keyed.width/cols)-Math.floor(x*keyed.width/cols),height:Math.floor((y+1)*keyed.height/rows)-Math.floor(y*keyed.height/rows)});const s=state.specs[y*cols+x];if(s){c.semanticId=s.id;c.name=s.label;}state.candidates.push(c);}catch(err){if(!(err as Error).message.includes('没有前景'))throw err;}}report='已按网格产生候选；名称仅按清单顺序建议，须逐件核对。';break;}
    case 'merge':{const ids=checkedIDs(),selected=state.candidates.filter(c=>ids.includes(c.id));if(selected.length<2)throw new Error('至少勾选两个属于同一部件的候选。');if(selected.some(c=>c.status==='approved'))throw new Error('请先撤回确认，再合并；已确认件不会被自动改写。');if(selected.some(c=>c.sheetId!==state.activeSheet))throw new Error('只能合并当前源图的候选。');const x=Math.min(...selected.map(c=>c.bounds.x)),y=Math.min(...selected.map(c=>c.bounds.y)),endX=Math.max(...selected.map(c=>c.bounds.x+c.bounds.width)),endY=Math.max(...selected.map(c=>c.bounds.y+c.bounds.height));state.candidates.push(candidateFrom({x,y,width:endX-x,height:endY-y}));selected.forEach(c=>c.status='archived');report='已按原图位置合并。请检查包围范围内是否混入其他素材。';break;}
    case 'mark-repair':{const ids=checkedIDs();state.candidates.filter(c=>ids.includes(c.id)).forEach(c=>c.status='repair');break;}
    case 'unarchive':{const c=[...state.candidates].reverse().find(c=>c.status==='archived');if(c)c.status='review';break;}
    case 'send-parts':{const approved=state.candidates.filter(c=>c.status==='approved'&&!c.imported);if(!approved.length)throw new Error('所有已确认件已经导入。为避免重复导入，请在画板继续编辑。');const qa=coverage(state);if(qa.missing.length&&!confirm(`还有 ${qa.missing.length} 个缺项。先导入 ${approved.length} 个已确认零件？`))break;await hooks.importAssets(approved.map(c=>({id:uid('asset'),name:c.semanticId,width:c.width,height:c.height,dataUrl:c.image,hasAlpha:true})));approved.forEach(c=>c.imported=true);root.close();break;}
    case 'download-parts':{const items=state.candidates.filter(c=>c.status==='approved');const entries=items.map(c=>({name:`parts/${c.semanticId}.png`,bytes:Uint8Array.from(atob(c.image.split(',')[1]),v=>v.charCodeAt(0))}));entries.push(textEntry('manifest.json',JSON.stringify({format:'ai-bone-parts',version:'0.3',backgroundPolicy:'chroma-only',coordinates:'source sheet pixels, not character setup',parts:items.map(({image,...c})=>({...c,file:`parts/${c.semanticId}.png`}))},null,2)));download('character-parts.zip',writeZip(entries),'application/zip');break;}
    case 'save-prep':download('character.prep.json',JSON.stringify(parsePreparation(state)),'application/json');break;
    case 'clear-prep':if(confirm('清空本地角色准备状态？不删除画板工程或云端任务。请先下载准备工程。')){state=newPreparation();original=keyed=null;step=0;}break;
    case 'connect':{apiURL=$<HTMLInputElement>('gateway-url').value.trim().replace(/\/$/,'');access=$<HTMLInputElement>('gateway-token').value.trim();const c=await api('/capabilities') as {providers:Provider[]};if(!Array.isArray(c.providers)||c.providers.length>20||c.providers.some(p=>!p||typeof p.id!=='string'||! /^[a-zA-Z0-9_-]{1,80}$/.test(p.id)||typeof p.label!=='string'||typeof p.model!=='string'||p.label.length>200||p.model.length>200||typeof p.generate!=='boolean'||typeof p.edit!=='boolean'))throw new Error('服务不是兼容的 Bone Studio 网关。');providers=c.providers;providerId=providers[0]?.id??'';try{localStorage.setItem('bone-gateway-url',apiURL);}catch{}await refreshJobs();break;}
    case 'disconnect':access='';providers=[];lastJobs=[];taskMessage='已退出，供应商密钥始终未发到浏览器。';break;
    case 'refresh-jobs':await refreshJobs();break;
   }
  });
 });
 root.addEventListener('input',e=>{const t=e.target as HTMLInputElement;switch(t.id){case 'prep-name':state.name=t.value;break;case 'prep-description':state.description=t.value;break;case 'gateway-token':access=t.value;return;case 'gateway-url':apiURL=t.value;return;default:return;}save();});
 root.addEventListener('change',e=>{if(processing)return;const t=e.target as HTMLInputElement;
  if(t.id==='inspect-bg'){const wrap=$('mask-wrap');wrap.className='mask-wrap '+t.value;drawMask();return;}
  if(t.dataset.semantic){const c=state.candidates.find(c=>c.id===t.dataset.semantic)!;c.semanticId=t.value;c.name=state.specs.find(s=>s.id===t.value)?.label??'未命名';c.status='review';save();render();return;}
  if(t.dataset.purpose){const p=t.dataset.purpose as Purpose;state.purposes=t.checked?[...new Set([...state.purposes,p])]:state.purposes.filter(v=>v!==p);if(!state.purposes.length)state.purposes=['head'];state.specs=specsFor(state.purposes);save();render();return;}
  if(t.id==='prep-view'){state.view=t.value;save();return;}if(t.id==='prep-color'){state.color=t.value;save();return;}if(t.id==='provider'){providerId=t.value;return;}
  if(t.id==='sheet-select'){state.activeSheet=t.value;void run(loadSheet);return;}
  const file=t.files?.[0];if(!file)return;void run(async()=>{
   if(t.id==='prep-open'){if(file.size>130*1024*1024)throw new Error('准备工程过大。');const next=parsePreparation(JSON.parse(await file.text()));if(state.characters.length&&!confirm('打开其他准备工程？当前状态将替换，请先备份。'))return;state=next;original=keyed=null;if(state.activeSheet)await loadSheet();step=0;return;}
   const r=await fileRaster(file);if(t.id==='prep-role-file'){addCharacter(state,rasterURL(r),r.width,r.height,file.name.slice(0,120));report='已保留原画。采用此版本后继续。';}
   else if(t.id==='prep-sheet-file')await newSheet(r,file.name);
  });
 });
 const open=():void=>{render();if(!root.open)root.showModal();};
 void stored().then(s=>{if(s&&!modified){state=s;report='已恢复上次角色准备状态。';if(state.activeSheet)void loadSheet().then(()=>{if(root.open)render();}).catch(e=>hooks.notice((e as Error).message,true));if(root.open)render();}}).catch(()=>{});
 root.addEventListener('cancel',()=>{if(processing)hooks.notice('当前图像处理仍会完成，重新打开可继续。');});
 return {open};
}
